namespace KidsLang.Domain;

// Entities follow BRD §12. GUID keys, UTC DateTime, JSON columns stored as strings via value converters.

public sealed class Parent
{
    public Guid Id { get; set; } = Guid.NewGuid();
    /// <summary>Always lower-case (collation differs between SQLite and PostgreSQL).</summary>
    public string Email { get; set; } = "";
    public string Name { get; set; } = "";
    /// <summary>E.164, e.g. +971501234567.</summary>
    public string Phone { get; set; } = "";
    public string PasswordHash { get; set; } = "";
    /// <summary>Hash of the 4-digit parent PIN (same hasher as the password).</summary>
    public string PinHash { get; set; } = "";
    public DateTime? EmailVerifiedAtUtc { get; set; }
    public DateTime? PhoneVerifiedAtUtc { get; set; }
    public DateTime ConsentGivenAtUtc { get; set; }
    public string Locale { get; set; } = "en";
    public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow;
    public List<ChildProfile> Children { get; set; } = [];
    public List<RefreshToken> RefreshTokens { get; set; } = [];
}

/// <summary>
/// A sign-up waiting for its two one-time codes (WhatsApp + email). Becomes a Parent once both are
/// verified; codes are stored hashed, expire after 10 minutes and allow 5 wrong tries.
/// </summary>
public sealed class PendingRegistration
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public string Name { get; set; } = "";
    public string Email { get; set; } = "";
    public string Phone { get; set; } = "";
    public string PasswordHash { get; set; } = "";
    public string PinHash { get; set; } = "";
    public string Locale { get; set; } = "en";
    public string EmailCodeHash { get; set; } = "";
    public string PhoneCodeHash { get; set; } = "";
    public int FailedAttempts { get; set; }
    public int Resends { get; set; }
    public DateTime CodesSentAtUtc { get; set; }
    public DateTime ExpiresAtUtc { get; set; }
    public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow;
}

public sealed class RefreshToken
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid ParentId { get; set; }
    public string TokenHash { get; set; } = "";
    public DateTime ExpiresAtUtc { get; set; }
    public DateTime? RevokedAtUtc { get; set; }
}

/// <summary>Children have a nickname and avatar only — no email, real name or location.</summary>
public sealed class ChildProfile
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid ParentId { get; set; }
    public string Nickname { get; set; } = "";
    public string AgeBand { get; set; } = "4-6";
    public AvatarConfig Avatar { get; set; } = new();
    public string? PicturePinHash { get; set; }
    public string TimeZone { get; set; } = "UTC";
    public int DailyLimitMinutes { get; set; } = 20;
    public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow;
}

public sealed class AvatarConfig
{
    public string Animal { get; set; } = "🦊";
    public string Color { get; set; } = "#c4b5fd";
    public string Item { get; set; } = "none";
}

public enum LessonStatus { InProgress, Mastered }

public sealed class LessonProgress
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid ChildId { get; set; }
    public string LessonId { get; set; } = "";
    public LessonStatus Status { get; set; } = LessonStatus.InProgress;
    public double BestScore { get; set; }
    public int Stars { get; set; }
    public int Attempts { get; set; }
    public bool UnlockedByParent { get; set; }
    public DateTime? MasteredAtUtc { get; set; }
}

/// <summary>Id is generated by the client so offline batches can be re-sent safely (idempotent).</summary>
public sealed class ActivityAttempt
{
    public Guid Id { get; set; }
    public Guid ChildId { get; set; }
    public string ActivityId { get; set; } = "";
    public string LessonId { get; set; } = "";
    public string ItemId { get; set; } = "";
    public bool IsCorrect { get; set; }
    public double? Score { get; set; }
    public DateTime CreatedAtUtc { get; set; }
}

public sealed class QuizAttempt
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid ChildId { get; set; }
    public string LessonId { get; set; } = "";
    public double Score { get; set; }
    public bool Passed { get; set; }
    public List<ItemResult> ItemResults { get; set; } = [];
    public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow;
}

public sealed class ItemMastery
{
    public Guid ChildId { get; set; }
    public string LearningItemId { get; set; } = "";
    public int LeitnerBox { get; set; } = 1;
    public int CorrectCount { get; set; }
    public int WrongCount { get; set; }
    public DateTime NextReviewAtUtc { get; set; }
    public DateTime? LastReviewedAtUtc { get; set; }
}

public sealed class Reward
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid ChildId { get; set; }
    public string Type { get; set; } = "star";
    public string RefId { get; set; } = "";
    public DateTime AwardedAtUtc { get; set; } = DateTime.UtcNow;
}
